spring:
  application:
    name: cloud-discovery-service
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adborja/tech-ecommerce-config.git
          clone-on-start: true
      enabled: false
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 8761

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 4
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 1
    initialInstanceInfoReplicationIntervalSeconds: 4
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${localhost}:${server.port}/eureka/

