spring:
  application:
    name: discovery-service
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

server:
  port: 8761

eureka:
  instance:
    hostname: cloud-discover-service-jbarrer
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: https://${eureka.instance.hostname}:${server.port}/eureka/

